cycling/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import *

app_name = "cycling"
urlpatterns = [
    re_path(
        r"^view_cell_id/(?P<cell_id>\d+)/(?P<cursor>[A-Z_]*)/$",
        view_cell_id,
        name = "view_cell_id",
    ),
    path("overview/", main_page, name = "main_page"),
    path("", index, name = "index"),
    path("admin/", admin.site.urls),
    path("filename_database/", include("filename_database.urls")),
    path("cell_database/", include("cell_database.urls")),
]

filename_database/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'filename_database'

urlpatterns = [
    path('', views.main_page, name='main_page'),
]

filename_database/forms.py
from django import forms
from filename_database.models import *
from datetime import date
from django.forms import BaseModelFormSet

class ParserFieldForm(forms.Form):

    experiment_type_search = forms.BooleanField(required=False)
    experiment_type = forms.ModelChoiceField(queryset=ExperimentType.objects.all(), required = False)

    student_search = forms.BooleanField(required=False)
    student = forms.CharField(required=False)

    cell_id_search = forms.BooleanField(required=False)
    cell_id = forms.IntegerField(required=False)

    start_cycle_search = forms.BooleanField(required=False)
    start_cycle = forms.IntegerField(required=False)

    voltage_search = forms.BooleanField(required=False)
    voltage = forms.FloatField(required=False)

    temperature_search = forms.BooleanField(required=False)
    temperature = forms.IntegerField(required=False)

    charger_search = forms.BooleanField(required = False)
    charger = forms.CharField(max_length=5, required = False)

    AC_search = forms.BooleanField(required=False)
    AC = forms.IntegerField(required=False)

    version_number_search = forms.BooleanField(required=False)
    version_number = forms.IntegerField(required=False)

    drive_profile_search = forms.BooleanField(required=False)
    drive_profile = forms.ModelChoiceField(queryset=ChargerDriveProfile.objects.all(), required = False)

    drive_profile_x_numerator_search = forms.BooleanField(required=False)
    drive_profile_x_numerator = forms.IntegerField(required=False)

    drive_profile_x_denominator_search = forms.BooleanField(required=False)
    drive_profile_x_denominator = forms.IntegerField(required=False)

    drive_profile_y_numerator_search = forms.BooleanField(required=False)
    drive_profile_y_numerator = forms.IntegerField(required=False)

    drive_profile_y_denominator_search = forms.BooleanField(required=False)
    drive_profile_y_denominator = forms.IntegerField(required=False)

    drive_profile_z_search = forms.BooleanField(required=False)
    drive_profile_z = forms.FloatField(required=False)

    test_date_search = forms.BooleanField(required=False)
    test_date = forms.DateField(widget=forms.SelectDateWidget(empty_label="--------", years=range(2000,date.today().year + 1)), required=False)



class SearchForm(forms.Form):

    filename1_search = forms.BooleanField(required=False)
    filename1 = forms.CharField(required=False)

    filename2_search = forms.BooleanField(required=False)
    filename2 = forms.CharField(required=False)

    filename3_search = forms.BooleanField(required=False)
    filename3 = forms.CharField(required=False)

    root1_search = forms.BooleanField(required=False)
    root1 = forms.CharField(required=False)

    root2_search = forms.BooleanField(required=False)
    root2 = forms.CharField(required=False)

    root3_search = forms.BooleanField(required=False)
    root3 = forms.CharField(required=False)

    show_valid = forms.BooleanField(required=False)
    show_invalid = forms.BooleanField(required=False)

    show_deprecated = forms.BooleanField(required=False)
    show_nondeprecated = forms.BooleanField(required=False)
    experiment_type = forms.ModelChoiceField(queryset=ExperimentType.objects.all(), required=True, empty_label=None)
    show_wrong_experiment_type = forms.BooleanField(required=False)
    page_number = forms.IntegerField(required=False)
    def set_page_number(self, page_number):
        data = self.data.copy()
        data['page_number'] = page_number
        self.data = data




class BaseExperimentTypeCorrectionFormSet(BaseModelFormSet):
    def add_fields(self, form, index):
        super().add_fields(form, index)
        form.fields["filename"] =forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly', 'size': 100}),
                                          required=False)
        form.fields["filename_id"] = forms.IntegerField(required=False,widget=forms.HiddenInput())
        form.fields["exclude"] = forms.BooleanField(required=False)
        form.fields["deprecate"] = forms.BooleanField(required=False)

        form.fields["last_modified"] = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'readonly': 'readonly'}),
                                          required=False)

        form.fields["filesize"] = forms.IntegerField(widget=forms.TextInput(attrs={'readonly': 'readonly', 'size': 5}),
                                          required=False)

        form.fields["old_experiment_type"] = forms.CharField(
            widget=forms.TextInput(attrs={'readonly':'readonly', 'size':50}),
            required=False)
        form.fields["reparse"] = forms.BooleanField(required=False)


class BaseMetadataCorrectionFormSet(BaseModelFormSet):
    def add_fields(self, form, index):
        super().add_fields(form, index)
        form.fields["filename"] =forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly', 'size': 100}),
                                          required=False)
        form.fields["filename_id"] = forms.IntegerField(required=False,widget=forms.HiddenInput())
        form.fields["exclude"] = forms.BooleanField(required=False)
        form.fields["deprecate"] = forms.BooleanField(required=False)

        form.fields["last_modified"] = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'readonly': 'readonly'}),
                                          required=False)

        form.fields["filesize"] = forms.IntegerField(widget=forms.TextInput(attrs={'readonly': 'readonly', 'size': 5}),
                                          required=False)

filename_database/views.py
from django.shortcuts import render
from django.forms import modelformset_factory, formset_factory
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .forms import *
from django.db.models import Q
from django import forms
from filename_database.parsing_functions import *
import datetime

def get_exclusions(experiment_type=None):

    exclude = ['drive_profile', 'experiment_type','drive_profile_x_numerator', 'drive_profile_x_denominator', 'drive_profile_y_numerator',
                    'drive_profile_y_denominator', 'drive_profile_z']


    if experiment_type is None or not experiment_type.cell_id_active:
        exclude.append('cell_id')

    if experiment_type is None or not experiment_type.start_cycle_active:
        exclude.append('start_cycle')

    if experiment_type is None or not experiment_type.voltage_active:
        exclude.append('voltage')

    if experiment_type is None or not experiment_type.temperature_active:
        exclude.append('temperature')

    if experiment_type is None or not experiment_type.AC_active:
        exclude.append('AC')
    if experiment_type is None or not experiment_type.AC_increment_active:
        exclude.append('AC_increment')

    if experiment_type is None or not experiment_type.version_number_active:
        exclude.append('version_number')

    return exclude


def get_headings(experiment_type=None, exclude=None, has_file_linked=True):
    headings = []
    possible_fields = [
        'charID',
        'cell_id',
        'start_cycle',
        'voltage',
        'temperature',
        'AC',
        'AC_increment',
        'version_number',
        'date',
    ]
    if has_file_linked:
        possible_fields += ['last_modified','filesize']

    for field in possible_fields:
        if field not in exclude:
            if field == 'voltage':
                field = experiment_type.voltage_name
            if field == 'temperature':
                field = experiment_type.temperature_name
            f = field
            headings.append(f)
    return headings


def main_page(request):
    ar ={

    }
    if request.method == 'POST':
        search_form = SearchForm(request.POST)
        if search_form.is_valid():
            ar['search_form'] = search_form
            experiment_type = search_form.cleaned_data['experiment_type']
            exclude = get_exclusions(experiment_type)
            headings = get_headings(experiment_type, exclude)
            headings = [ h.replace('_', ' ') for h in headings]
            MetadataEditForm = modelformset_factory(
                ValidMetadata,
                formset=BaseMetadataCorrectionFormSet,
                exclude=exclude,
                widgets={
                    'date': forms.SelectDateWidget(empty_label="Nothing", years=range(2000, datetime.date.today().year + 1)),
                    'charID':forms.TextInput(attrs={'size': 5})}
            )

            ExperimentTypeEditForm = modelformset_factory(
                ValidMetadata,
                formset=BaseExperimentTypeCorrectionFormSet,
                exclude=get_exclusions()+["experiment_type", 'date', 'charID'],
            )

            ValidMetadataForm = modelformset_factory(
                ValidMetadata,
                exclude=get_exclusions(experiment_type) + ["experiment_type"],
                widgets={
                    'date': forms.SelectDateWidget(empty_label="Nothing",
                                                   years=range(2000, datetime.date.today().year + 1)),
                    'charID': forms.TextInput(attrs={'size': 5})},
                extra=1
            )

            ar['search_form'] = search_form

            if 'change_exp_type' in request.POST:
                valid_metadata_formset = ValidMetadataForm()
                ar['metadata_edit_formset'] = valid_metadata_formset
                ar['make_changes'] = 'show_filename'
                headings = get_headings(experiment_type, get_exclusions(experiment_type), has_file_linked=False)
                headings = [h.replace('_', ' ') for h in headings]
                print(headings)
                ar['headings'] = headings

            elif 'search_and_fix_metadata' in request.POST:
                q = Q()
                if search_form.cleaned_data['show_valid'] and not search_form.cleaned_data['show_invalid']:
                    q = Q(is_valid=True)
                elif not search_form.cleaned_data['show_valid'] and search_form.cleaned_data['show_invalid']:
                    q = Q(is_valid=False)

                if search_form.cleaned_data['show_deprecated'] and not search_form.cleaned_data[
                    'show_nondeprecated']:
                    q = q & Q(deprecated=True)
                elif not search_form.cleaned_data['show_deprecated'] and search_form.cleaned_data[
                        'show_nondeprecated']:
                    q = q & Q(deprecated=False)
                if search_form.cleaned_data['filename1_search']:
                    q = q & Q(filename__icontains=search_form.cleaned_data['filename1'])
                if search_form.cleaned_data['filename2_search']:
                    q = q & Q(filename__icontains=search_form.cleaned_data['filename2'])
                if search_form.cleaned_data['filename3_search']:
                    q = q & Q(filename__icontains=search_form.cleaned_data['filename3'])

                if search_form.cleaned_data['root1_search']:
                    q = q & Q(root__icontains=search_form.cleaned_data['root1'])
                if search_form.cleaned_data['root2_search']:
                    q = q & Q(root__icontains=search_form.cleaned_data['root2'])
                if search_form.cleaned_data['root3_search']:
                    q = q & Q(root__icontains=search_form.cleaned_data['root3'])

                if search_form.cleaned_data['show_wrong_experiment_type']:
                    q = q & ~Q(valid_metadata__experiment_type=experiment_type)
                    total_query = DatabaseFile.objects.filter(q)
                else:
                    q = q & Q(valid_metadata__experiment_type=experiment_type)
                    total_query = DatabaseFile.objects.filter(q)
                initial = []
                pn = search_form.cleaned_data['page_number']
                if pn is None:
                    pn = 1
                    search_form.set_page_number(pn)
                n = total_query.count()
                max_page = int(n / 15)
                if (n % 15) != 0:
                    max_page += 1

                if pn > max_page:
                    pn = max_page
                    search_form.set_page_number(pn)

                if pn < 1:
                    pn = 1
                    search_form.set_page_number(pn)

                if search_form.cleaned_data['show_wrong_experiment_type']:
                    for db_filename in total_query[(pn - 1) * 15:min(n, (pn) * 15)]:
                        my_initial = {
                            "filename": db_filename.filename,
                            "filename_id": db_filename.id,
                            "exclude": True,
                            'deprecate': db_filename.deprecated,
                            "reparse": True,
                            "last_modified": db_filename.last_modified,
                            "filesize": '{}'.format(int(db_filename.filesize / 1024))
                        }
                        if db_filename.valid_metadata is None:
                            my_initial["old_experiment_type"] = ''
                        else:
                            my_initial["old_experiment_type"] = db_filename.valid_metadata.experiment_type.__str__()
                        print(my_initial)

                        initial.append(my_initial)

                    ExperimentTypeEditForm = modelformset_factory(
                        ValidMetadata,
                        formset=BaseExperimentTypeCorrectionFormSet,
                        exclude=get_exclusions()+["experiment_type", 'date', 'charID'],
                        extra=len(initial)
                    )

                    experiment_type_edit_formset = ExperimentTypeEditForm(queryset=DatabaseFile.objects.none(),
                                                             initial=initial)

                    ar['metadata_edit_formset'] = experiment_type_edit_formset
                    ar['make_changes'] = 'make_changes_to_experiment_type'
                    headings = get_headings(None, get_exclusions()+['date', 'charID'])
                    headings = [h.replace('_', ' ') for h in headings] + ['old_experiment_type', 'reparse']
                    ar['headings'] = headings
                else:
                    for db_filename in total_query[(pn - 1) * 15:min(n, (pn) * 15)]:
                        my_initial = {
                            "filename": db_filename.filename,
                            "filename_id": db_filename.id,
                            "exclude": True,
                            'deprecate': db_filename.deprecated,
                            "experiment_type": experiment_type,
                            "charID": db_filename.valid_metadata.charID,
                            "cell_id": db_filename.valid_metadata.cell_id,
                            "start_cycle": db_filename.valid_metadata.start_cycle,
                            "voltage": db_filename.valid_metadata.voltage,
                            "temperature": db_filename.valid_metadata.temperature,
                            "AC": db_filename.valid_metadata.AC,
                            "AC_increment": db_filename.valid_metadata.AC_increment,
                            "version_number": db_filename.valid_metadata.version_number,
                            "date": db_filename.valid_metadata.date,
                            "last_modified": db_filename.last_modified,

filename_database/templates/filename_database/form_interface.html
{% extends "base_generic.html" %}

{% load static %}
{% block content %}


<style>
table {
    border-collapse:collapse;

}
table, th, td {
    border:1px solid black;}


</style>


<h1>All Files</h1>


<!-- First step: Selecting drive profile and experiment type-->



<form action="{% url 'filename_database:main_page' %}" method="post">
    {% csrf_token %}



{% if search_form %}
<table>

    <table>
    <tr>
        <th> </th> <th>Use in search?</th> <th>Value to search</th>
    <tr>
        <th>Keyword in Filename</th> <td>{{search_form.filename1_search}}</td> <td>{{search_form.filename1}}</td>
    </tr>
    <tr>
        <th>Keyword in Filename</th> <td>{{search_form.filename2_search}}</td> <td>{{search_form.filename2}}</td>
    </tr>
    <tr>
        <th>Keyword in Filename</th> <td>{{search_form.filename3_search}}</td> <td>{{search_form.filename3}}</td>
    </tr>


    <tr>
        <th>Keyword in Root</th> <td>{{ search_form.root1_search }}</td><td>{{ search_form.root1 }}</td>
    </tr>
    <tr>
        <th>Keyword in Root</th> <td>{{ search_form.root2_search }}</td><td>{{ search_form.root2 }}</td>
    </tr>
    <tr>
        <th>Keyword in Root</th> <td>{{ search_form.root3_search }}</td><td>{{ search_form.root3 }}</td>
    </tr>


    </table>

    <table>
    <tr>
        <th>only valid files</th> <td>{{search_form.show_valid}}</td>
    </tr>
    <tr>
        <th>only invalid files</th> <td>{{search_form.show_invalid}}</td>
    </tr>

    <tr>
        <th>only deprecated files</th> <td>{{search_form.show_deprecated}}</td>
    </tr>

    <tr>
        <th>only non-deprecated files</th> <td>{{search_form.show_nondeprecated}}</td>
    </tr>

    <tr>
        <th>Select Experiment Type</th> <td>{{search_form.experiment_type}}</td>
    </tr>
    <tr>
        <th>Display files with a different experiment type</th> <td>{{search_form.show_wrong_experiment_type}}</td>
    </tr>


    </table>
<br>

 <tr>
    <th>Display Page: </th> <td>{{search_form.page_number}}</td>
</tr>
<input type="submit" name = 'search_and_fix_metadata' value="Search database and fix errors">
<input type="submit" name = 'change_exp_type' value="Get Filename with Selected Experiment Type">

</table>



{% endif %}









{% if metadata_edit_formset%}
{% csrf_token %}
{{ metadata_edit_formset.management_form }}
{% if make_changes != 'show_filename' %}
    Showing page {{page_number}}/{{max_page_number}}.
{% endif %}
    <table>
    <col width = "200">
    <col width = "5">

            <tr>
                {% if make_changes != 'show_filename' %}
                    <th>Filename</th>

                    <th>Exclude</th>

                    <th>Deprecate</th>
                {% endif %}

                {% for heading in headings %}
                    {% if heading == "charID" %}
                        <th> CharID </th>
                    {% elif heading == "filesize" %}
                        <th>File Size (KB)</th>
                    {%else%}
                        <th> {{ heading | title }} </th>
                    {%endif%}
                {% endfor %}
            </tr>

        {% for form in metadata_edit_formset %}

            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}

            <tr>
                {% if make_changes != 'show_filename' %}

                    <td>{{ form.filename }}</td>
                    <td>{{ form.exclude }}</td>
                    <td>{{ form.deprecate }}</td>
                {% endif %}

                {% for field in form.visible_fields %}
                    {% if field.name == "id" or field.name == 'filename' or field.name == 'exclude' or field.name == 'deprecate'%}
                    {% else %}
                        <td> {{ field }}  </td>
                    {% endif %}
                {% endfor %}

            </tr>


        {% endfor %}

    </table>




    <input type="submit" name = {{make_changes}} value = "Make Changes">

</form>

{% endif %}


{% if filename_to_show %}
<h3>Valid Files</h3>
    {% for f in filename_to_show %}
        {{f}} <br>
    {% endfor %}
{% endif %}

{% endblock %}