cell_database/urls.py
from django.contrib import admin
from django.urls import path
from . import views

from django.conf.urls import url


app_name = 'cell_database'

urlpatterns = [
    url(r'^define/(?P<mode>\w+)/$', views.define_page, name='define_page'),
    path('search/', views.search_page, name='search_page'),
    url(r'^define_wet_cell_bulk/(?P<predefined>\w+)/$', views.define_wet_cell_bulk, name='define_wet_cell_bulk'),
    path('delete/', views.delete_page, name='delete_page'),
    path('dataset_overview/', views.dataset_overview, name='dataset_overview'),
    url(r'^view_dataset/(?P<pk>\d+)/$', views.view_dataset, name='view_dataset'),

]

cycling/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import *

app_name = "cycling"
urlpatterns = [
    re_path(
        r"^view_cell_id/(?P<cell_id>\d+)/(?P<cursor>[A-Z_]*)/$",
        view_cell_id,
        name = "view_cell_id",
    ),
    path("overview/", main_page, name = "main_page"),
    path("", index, name = "index"),
    path("admin/", admin.site.urls),
    path("filename_database/", include("filename_database.urls")),
    path("cell_database/", include("cell_database.urls")),
]

cell_database/views.py
from django.shortcuts import render, render_to_response
from django.forms import modelformset_factory, formset_factory
from django.db.models import Q, F, Func, Count,Exists, OuterRef
from .forms import *
from .models import *
from plot import plot_cycling_direct
from django import forms
import re



def conditional_register(ar, name, content):
    if name not in ar.keys():
        ar[name] = content



def define_page(request, mode=None):
    ar = {'mode':mode}
    def define_simple(post, content=None):
        if content in ['electrolyte', 'electrode', 'separator']:
            components = None
            components_lot = None

            if content == 'electrolyte':
                ElectrolyteCompositionFormset = formset_factory(
                    ElectrolyteCompositionForm,
                    extra=10
                )
                simple_form = ElectrolyteForm(request.POST, prefix='electrolyte-form')
                component_string = 'molecule'
            elif content == 'electrode':
                ElectrodeCompositionFormset = formset_factory(
                    ElectrodeCompositionForm,
                    extra=10
                )
                simple_form = ElectrodeForm(request.POST, prefix='electrode-form')
                component_string = 'material'

            elif content == 'separator':
                SeparatorCompositionFormset = formset_factory(
                    SeparatorCompositionForm,
                    extra=10
                )
                simple_form = SeparatorForm(request.POST, prefix='separator-form')
                component_string = 'material'


            simple_form_string = 'define_{}_form'.format(content)
            composition_formset_string = '{}_composition_formset'.format(content)

            if not simple_form.is_valid():
                return None
            else:
                ar[simple_form_string] = simple_form




                my_composite = Composite(
                    proprietary=simple_form.cleaned_data['proprietary'],
                    proprietary_name=simple_form.cleaned_data['proprietary_name'],
                    notes=simple_form.cleaned_data['notes'],
                )
                if content == 'electrolyte':
                    my_composite.composite_type = ELECTROLYTE
                elif content == 'electrode':
                    my_composite.composite_type = simple_form.cleaned_data['composite_type']
                    my_composite.composite_type_name = simple_form.cleaned_data['composite_type_name']

                if content == 'separator':
                    my_composite.composite_type = SEPARATOR

                if not my_composite.proprietary:
                    if content == 'electrolyte':
                        composition_formset = ElectrolyteCompositionFormset(request.POST,
                                                                prefix='electrolyte-composition-formset')
                    if content == 'electrode':
                        composition_formset = ElectrodeCompositionFormset(request.POST,
                                                                prefix='electrode-composition-formset')
                    if content == 'separator':
                        composition_formset = SeparatorCompositionFormset(request.POST,
                                                                prefix='separator-composition-formset')

                    ar[composition_formset_string] = composition_formset

                    components = []
                    components_lot = []
                    for form in composition_formset:
                        validation_step = form.is_valid()
                        if validation_step:

                            if not component_string in form.cleaned_data.keys():
                                continue
                            mol_s = form.cleaned_data[component_string]
                            my_id, lot_type = decode_lot_string(mol_s)
                            if lot_type == LotTypes.none:
                                continue
                            value, unknown = unknown_numerical(form.cleaned_data['ratio'])
                            if not unknown and value is None:
                                continue
                            h = {'ratio': value}
                            if lot_type == LotTypes.lot:
                                h['component_lot']= ComponentLot.objects.get(id=my_id)
                                components_lot.append(h)
                            if lot_type == LotTypes.no_lot:

                                h['component']= Component.objects.get(id=my_id)
                                components.append(h)

            my_target = simple_form.cleaned_data['override_target']

            if my_target is not None:
                my_target = my_target.id

            return my_composite.define_if_possible(
                components=components,
                components_lot=components_lot,
                target=my_target
            )

        if content in ['material','molecule','separator_material']:
            atoms = None
            if content == 'material':
                ActiveMaterialCompositionFormset = formset_factory(
                    ElectrodeMaterialStochiometryForm,
                    extra=10
                )
                simple_form = ElectrodeMaterialForm(request.POST, prefix='electrode-material-form')
            elif content == 'molecule':
                simple_form = ElectrolyteMoleculeForm(post, prefix='electrolyte-molecule-form')
            elif content == 'separator_material':
                simple_form = SeparatorMaterialForm(request.POST, prefix='separator-material-form')

            simple_form_string = 'define_{}_form'.format(content)

            if not simple_form.is_valid():
                return None
            else:
                ar[simple_form_string] = simple_form
                if content in ['material']:
                    composite_type = simple_form.cleaned_data['composite_type']
                    composite_type_name = simple_form.cleaned_data['composite_type_name']
                if content == 'molecule':
                    composite_type = ELECTROLYTE
                    composite_type_name = False
                if content == 'separator_material':
                    composite_type = SEPARATOR
                    composite_type_name = False

                if content in ['material','molecule']:
                    component_type = simple_form.cleaned_data['component_type']
                    component_type_name = simple_form.cleaned_data['component_type_name']
                if content == 'separator_material':
                    component_type = SEPARATOR_MATERIAL
                    component_type_name = False

                my_component = Component(
                    proprietary = simple_form.cleaned_data['proprietary'],
                    proprietary_name=simple_form.cleaned_data['proprietary_name'],
                    notes=simple_form.cleaned_data['notes'],
                    component_type=component_type,
                    component_type_name=component_type_name,
                    composite_type=composite_type,
                    composite_type_name=composite_type_name,
                )

                if content != 'molecule':
                    my_id, lot_type = decode_lot_string(
                        simple_form.cleaned_data['coating']
                    )

                    my_component.coating_lot = None

                    if lot_type == LotTypes.unknown:
                        my_component.coating_lot = None
                    else:
                        if lot_type == LotTypes.no_lot:
                            my_component.coating_lot = get_lot(
                                Coating.objects.get(id=my_id),
                                None,
                                type='coating'
                            )
                        elif lot_type == LotTypes.lot:
                            my_component.coating_lot = CoatingLot.objects.get(id=my_id)

                    my_component.particle_size = simple_form.cleaned_data['particle_size']
                    my_component.particle_size_name = simple_form.cleaned_data['particle_size_name']
                    my_component.preparation_temperature = simple_form.cleaned_data['preparation_temperature']
                    my_component.preparation_temperature_name = simple_form.cleaned_data[
                                                       'preparation_temperature_name']
                    my_component.coating_lot_name = simple_form.cleaned_data['coating_lot_name']


                if content == 'material':
                    my_component.single_crystal = simple_form.cleaned_data['single_crystal']
                    my_component.single_crystal_name = simple_form.cleaned_data['single_crystal_name']
                    my_component.turbostratic_misalignment = simple_form.cleaned_data['turbostratic_misalignment']
                    my_component.turbostratic_misalignment_name = simple_form.cleaned_data[
                        'turbostratic_misalignment_name']
                    my_component.natural = simple_form.cleaned_data['natural']
                    my_component.natural_name = simple_form.cleaned_data['natural_name']


                my_component.smiles = simple_form.cleaned_data['smiles']
                my_component.smiles_name = simple_form.cleaned_data['smiles_name']

                if not my_component.proprietary and content=='material':
                    active_material_composition_formset = ActiveMaterialCompositionFormset(
                        request.POST,
                        prefix='active-material-composition-formset'
                    )
                    atoms = []
                    for form in active_material_composition_formset:

cell_database/templates/cell_database/coating.html
<table>
    <tr>
        <th></th><th>Value</th><th>Use in Name?</th>
    </tr>
    <tr>
        <th>Notes: </th><td>{{define_coating_form.notes}}</td>
    </tr>
    <tr>
        <th>Proprietary: </th><td>{{define_coating_form.proprietary}}</td> <td>{{define_coating_form.proprietary_name}} </td>
    </tr>
    <tr>
        <th>Description: </th><td>{{define_coating_form.description}}</td><td>{{define_coating_form.description_name}}</td>
    </tr>

</table>

Override Target (leave blank to define a brand new dry cell):
<br>
{{define_coating_form.override_target}}
<br>

cell_database/templates/cell_database/dataset_overview.html
{% extends "base_generic.html" %}

{% load static %}
{% block content %}


<style>
table {
    border-collapse:collapse;

}
table, th, td {
    border:1px solid black;}


</style>

<form action="{% url 'cell_database:dataset_overview' %}" method="post">
    {% csrf_token %}
    {{ create_dataset_form }}
    <input type="submit" name = 'define_dataset' value="Create a new Dataset.">
</form>
<br>
{{ message }}

{% if zipped_data %}
    <table>
        <caption>Registered Datasets</caption>
        <tr>
            <th>Name</th>
            <th>Number of cells</th>

        </tr>
        {% for dataset, count in zipped_data %}
        <tr>
            <td><a href="{% url 'cell_database:view_dataset' pk=dataset.id %}">{{ dataset.name }}</a></td>
            <td>{{ count }}</td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No datasets were registered.</p>
{% endif %}

{% endblock %}

cell_database/templates/cell_database/define_page.html
{% extends "base_generic.html" %}

{% load static %}
{% block content %}


<style>
table {
    border-collapse:collapse;

}
table, th, td {
    border:1px solid black;}


</style>


<form action="{% url 'cell_database:define_page' mode=mode %}" method="post">
    {% csrf_token %}



    <table>

    {% if define_coating_form %}
        <td valign="top">
        <h1>Coating</h1>
            {% include "cell_database/coating.html"  %}
        <input type="submit" name = 'define_coating' value="Define Coating">

        {% if define_coating_lot_form %}
            {% include "cell_database/lot_info.html" with lot_info_form=define_coating_lot_form predefined=define_coating_lot_form.predefined_coating predefined_label="Predefined Coating" %}
            <input type="submit" name = 'define_coating_lot' value="Define Coating Lot">
        {% endif %}
        </td>
    {% endif %}






        {% if define_molecule_form %}
            <td valign="top">
            <h1>Molecule</h1>
                {% include "cell_database/molecule.html"  %}
            <input type="submit" name = 'define_molecule' value="Define Electrolyte Molecule">

            {% if define_molecule_lot_form %}
                {% include "cell_database/lot_info.html" with lot_info_form=define_molecule_lot_form predefined=define_molecule_lot_form.predefined_molecule predefined_label="Predefined Molecule" %}
            <input type="submit" name = 'define_molecule_lot' value="Define Electrolyte Molecule Lot">
            {% endif %}
            </td>
        {% endif %}


        {% if define_electrolyte_form %}
            <td valign="top">
            <h1>Electrolyte</h1>
                {% include "cell_database/electrolyte.html"  %}
            {% if electrolyte_composition_formset %}
                {% csrf_token %}
                {{ electrolyte_composition_formset.management_form }}
                <table>
                    <tr>
                        <td>Molecule</td><td>Amount</td>
                    </tr>
                    {% for form in electrolyte_composition_formset%}
                        {% for hid in form.hidden_fields %}
                            {{ hid }}
                        {% endfor %}
                        <tr>
                            <td>{{ form.molecule}}</td><td>{{ form.ratio}}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
            <input type="submit" name = 'define_electrolyte' value="Define Electrolyte">
            {% if define_electrolyte_lot_form %}
            {% include "cell_database/lot_info.html" with lot_info_form=define_electrolyte_lot_form predefined=define_electrolyte_lot_form.predefined_electrolyte predefined_label="Predefined Electrolyte" %}
            <input type="submit" name = 'define_electrolyte_lot' value="Define Electrolyte Lot">
        {% endif %}
            </td>
        {% endif %}

        {% if define_material_form %}
        <td valign="top">
        <h1>Material</h1>
            {% include "cell_database/material.html" %}
                {% if active_material_composition_formset %}
                    {% csrf_token %}
                    {{ active_material_composition_formset.management_form }}
                    <table>
                        <tr>
                            <td>Atom</td><td>Stochiometry</td>
                        </tr>
                        {% for form in active_material_composition_formset%}
                            <tr>
                                <td>{{ form.atom}}</td><td>{{ form.stochiometry}}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
            <input type="submit" name = 'define_material' value="Define Material">
            {% if define_material_lot_form %}
            {% include "cell_database/lot_info.html" with lot_info_form=define_material_lot_form predefined=define_material_lot_form.predefined_material predefined_label="Predefined Material" %}
            <input type="submit" name = 'define_material_lot' value="Define Material Lot">
            {% endif %}
        </td>
        {% endif %}




        {% if define_electrode_form%}
        <td valign="top">
        <h1>Electrode</h1>
            {% include "cell_database/electrode.html" %}
            {% if electrode_composition_formset %}
                {% csrf_token %}
                {{ electrode_composition_formset.management_form }}
                <table>
                    <tr>
                        <td>Material</td><td>Amount</td>
                    </tr>
                    {% for form in electrode_composition_formset%}
                        <tr>
                            <td>{{ form.material}}</td><td>{{ form.ratio}}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
            <input type="submit" name = 'define_electrode' value="Define Electrode">
            {% if define_electrode_lot_form %}
            {% include "cell_database/lot_info.html" with lot_info_form=define_electrode_lot_form predefined=define_electrode_lot_form.predefined_electrode predefined_label="Predefined Electrode" %}

                <input type="submit" name = 'define_electrode_lot' value="Define Electrode Lot">
            {% endif %}
        </td>
        {% endif %}


        {% if define_separator_material_form %}
        <td valign="top">
        <h3>Separator Material</h3>
                {% include "cell_database/separator_material.html" %}
            <input type="submit" name = 'define_separator_material' value="Define Separator Material">
            {% if define_separator_material_lot_form %}
            {% include "cell_database/lot_info.html" with lot_info_form=define_separator_material_lot_form predefined=define_separator_material_lot_form.predefined_separator_material predefined_label="Predefined Separator Material" %}

            <input type="submit" name = 'define_separator_material_lot' value="Define Separator Material Lot">
            {% endif %}
        </td>
            {% endif %}


        {% if define_separator_form  %}
        <td valign="top">
        <h3>Separator</h3>
            {% include "cell_database/separator.html" %}
            {% if separator_composition_formset %}
                {% csrf_token %}
                {{ separator_composition_formset.management_form }}
                <table>
                    <tr>
                        <td>Material</td><td>Amount</td>
                    </tr>
                    {% for form in separator_composition_formset%}
                        <tr>
                            <td>{{ form.material}}</td><td>{{ form.ratio}}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
            <input type="submit" name = 'define_separator' value="Define Separator">
            {% if define_separator_lot_form %}

                {% include "cell_database/lot_info.html" with lot_info_form=define_separator_lot_form predefined=define_separator_lot_form.predefined_separator predefined_label="Predefined Separator" %}
                <input type="submit" name = 'define_separator_lot' value="Define Separator Lot">
            {% endif %}
        </td>
        {% endif %}

    {% if define_dry_cell_form and define_dry_cell_geometry_form and define_cathode_geometry_form and define_anode_geometry_form and define_separator_geometry_form%}
        <td valign="top">
        <h1>Dry Cell</h1>
            {% include "cell_database/dry_cell.html" %}
            <input type="submit" name = 'define_dry_cell' value="Define Dry Cell">
            {% if define_dry_cell_lot_form %}
            {% include "cell_database/lot_info.html" with lot_info_form=define_dry_cell_lot_form predefined=define_dry_cell_lot_form.predefined_dry_cell predefined_label="Predefined Dry Cell" %}

                <input type="submit" name = 'define_dry_cell_lot' value="Define Dry Cell Lot (AKA Box)">
            {% endif %}
        </td>
        {% endif %}


    </table>

</form>



{% endblock %}

cell_database/templates/cell_database/delete_page.html
{% extends "base_generic.html" %}

{% load static %}
{% block content %}


<style>
table {
    border-collapse:collapse;

}
table, th, td {
    border:1px solid black;}


</style>


<form action="{% url 'cell_database:delete_page' %}" method="post">
    {% csrf_token %}


    {% if form %}
        {{ form.as_p }}
        <input type='submit' name = 'delete_all_selected' value="Delete All Selected">
    {% endif %}

</form>



{% endblock %}

cell_database/templates/cell_database/dry_cell.html
<table>
    <tr>
        <th></th><th>Value</th><th>Use in Name?</th>
    </tr>
    <tr>
        <th>Notes: </th><td>{{define_dry_cell_form.notes}}</td>
    </tr>
    <tr>
        <th>Proprietary: </th><td>{{define_dry_cell_form.proprietary}}</td> <td>{{define_dry_cell_form.proprietary_name}} </td>
    </tr>
    <tr>
        <th>Cathode: </th><td>{{define_dry_cell_form.cathode}}</td> <td>{{define_dry_cell_form.cathode_name}} </td>
    </tr>
    <tr>
        <th>Cathode Loading: </th><td>{{define_cathode_geometry_form.loading}}<br>{{define_cathode_geometry_form.loading.help_text}}</td> <td>{{define_cathode_geometry_form.loading_name}} </td>
    </tr>
    <tr>
        <th>Cathode Density: </th><td>{{define_cathode_geometry_form.density}}<br>{{define_cathode_geometry_form.density.help_text}}</td> <td>{{define_cathode_geometry_form.density_name}} </td>
    </tr>
    <tr>
        <th>Cathode Thickness: </th><td>{{define_cathode_geometry_form.thickness}}<br>{{define_cathode_geometry_form.thickness.help_text}}</td> <td>{{define_cathode_geometry_form.thickness_name}} </td>
    </tr>

    <tr>
        <th>Anode: </th><td>{{define_dry_cell_form.anode}}</td> <td>{{define_dry_cell_form.anode_name}} </td>
    </tr>
    <tr>
        <th>Anode Loading: </th><td>{{define_anode_geometry_form.loading}}<br>{{define_anode_geometry_form.loading.help_text}}</td> <td>{{define_anode_geometry_form.loading_name}} </td>
    </tr>
    <tr>
        <th>Anode Density: </th><td>{{define_anode_geometry_form.density}}<br>{{define_anode_geometry_form.density.help_text}}</td> <td>{{define_anode_geometry_form.density_name}} </td>
    </tr>
    <tr>
        <th>Anode Thickness: </th><td>{{define_anode_geometry_form.thickness}}<br>{{define_anode_geometry_form.thickness.help_text}}</td> <td>{{define_anode_geometry_form.thickness_name}} </td>
    </tr>


    <tr>
        <th>Separator: </th><td>{{define_dry_cell_form.separator}}</td> <td>{{define_dry_cell_form.separator_name}} </td>
    </tr>
    <tr>
        <th>Separator Thickness: </th><td>{{define_separator_geometry_form.thickness}}<br>{{define_separator_geometry_form.thickness.help_text}}</td> <td>{{define_separator_geometry_form.thickness_name}} </td>
    </tr>
    <tr>
        <th>Separator Width: </th><td>{{define_separator_geometry_form.width}}<br>{{define_separator_geometry_form.width.help_text}}</td> <td>{{define_separator_geometry_form.width_name}} </td>
    </tr>

    <tr>
        <th>Geometry Category: </th><td>{{define_dry_cell_geometry_form.geometry_category}}<br>{{define_dry_cell_geometry_form.geometry_category.help_text}}</td> <td>{{define_dry_cell_geometry_form.geometry_category_name}} </td>
    </tr>

    <tr>
        <th>Width: </th><td>{{define_dry_cell_geometry_form.width}}<br>{{define_dry_cell_geometry_form.width.help_text}}</td> <td>{{define_dry_cell_geometry_form.width_name}} </td>
    </tr>
    <tr>
        <th>Length: </th><td>{{define_dry_cell_geometry_form.length}}<br>{{define_dry_cell_geometry_form.length.help_text}}</td> <td>{{define_dry_cell_geometry_form.length_name}} </td>
    </tr>
    <tr>
        <th>Thickness: </th><td>{{define_dry_cell_geometry_form.thickness}}<br>{{define_dry_cell_geometry_form.thickness.help_text}}</td> <td>{{define_dry_cell_geometry_form.thickness_name}} </td>
    </tr>


</table>

Override Target (leave blank to define a brand new dry cell):
<br>
{{define_dry_cell_form.override_target}}
<br>

cell_database/templates/cell_database/search_page.html
{% extends "base_generic.html" %}

{% load static %}
{% block content %}


<style>
table {
    border-collapse:collapse;

}
table, th, td {
    border:1px solid black;}


</style>


<h1>Search Stuff</h1>



<form action="{% url 'cell_database:search_page' %}" method="post">
    {% csrf_token %}
    <table>
        <tr>

            {%if search_wet_cell_form %}
                Display Page: {{search_wet_cell_form.page_number}}
            {%endif%}
            <input type="submit" name = 'preview_wet_cell' value="Preview Wet Cell">


            {%if wet_cell_preview_formset %}
                {% csrf_token %}
                {{ wet_cell_preview_formset.management_form }}

                {% if not wet_cell_preview_formset|length == 0%}
                    Showing page {{page_number}}/{{max_page_number}}.
                    <table>
                        <tr>
                            <th>Wet Cell</th> <th>Exclude ?</th>
                        </tr>
                    {% for form in wet_cell_preview_formset %}
                        {% for hidden in form.hidden_fields %}
                            {{hidden}}
                        {% endfor %}
                        <tr>
                            <td>{{ form.wet_cell}}</td><td>{{ form.exclude}}</td>
                        </tr>
                    {% endfor %}
                    </table>
                    {% if dataset_form %}
                        {{ dataset_form }}
                    {% endif %}
                    <input type="submit" name = 'register_wet_cells_to_dataset' value="Register to Dataset">
                {% endif %}
            {% endif %}

        </tr>
        <tr>
            <table>
            {% if electrolyte_form %}
            <td valign="top">
            <h2>Electrolyte</h2>
                <input type="submit" name = 'preview_electrolyte' value="Preview Electrolyte">
                {%if preview_electrolytes %}
                    {% if not preview_electrolytes|length == 0%}
                        <table>
                            <tr>
                                <th>Preview Electrolytes</th>
                            </tr>
                            {% for electrolyte in preview_electrolytes %}
                                <tr>
                                    <td>{{electrolyte}}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    {% endif %}
                {% endif %}

                <table>{{ electrolyte_form.as_table }}</table>
                {% if electrolyte_composition_formset %}
                    {% csrf_token %}
                    {{ electrolyte_composition_formset.management_form }}
                    <table>
                        <tr>
                            <th>Molecule</th><th>Must have?</th><th>Amount</th><th>Tolerance</th>
                        </tr>
                        {% for form in electrolyte_composition_formset%}
                            <tr>
                                <td>{{ form.molecule}}</td><td>{{form.must_type}}</td><td>{{ form.ratio}}</td><td>{{ form.tolerance}}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}

            </td>
        {% endif %}


        {% if search_dry_cell %}
            <td valign="top">
            <h2>Dry Cell</h2>
                 <input type="submit" name = 'preview_dry_cell' value="Preview Dry Cell">
                {%if preview_dry_cells %}
                    {% if not preview_dry_cells|length == 0%}
                        <table>
                            <tr>
                                <th>Preview Dry Cells</th>
                            </tr>
                            {% for dry_cell in preview_dry_cells %}
                                <tr>
                                    <td>{{dry_cell}}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    {% endif %}
                {% endif %}
                <table>{{ search_dry_cell.as_table }}</table>
                {% if dry_cell_scalars %}
                    {% csrf_token %}
                    {{ dry_cell_scalars.management_form }}
                    <table>
                        <tr>
                            <th>Field Name</th><th>Amount</th><th>Tolerance</th><th>Exclude Missing Values</th>
                        </tr>
                        {% for form in dry_cell_scalars%}
                            <tr>
                                <td>{{ form.name}}</td><td>{{form.scalar}}</td><td>{{ form.tolerance}}</td><td>{{ form.exclude_missing}}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}

            </td>
        {% endif %}
        </table>
        </tr>
    </table>

</form>



{% endblock %}

cell_database/templates/cell_database/view_dataset.html
{% extends "base_generic.html" %}

{% load static %}
{% block content %}


<style>
table {
    border-collapse:collapse;

}
table, th, td {
    border:1px solid black;}


</style>
{% if zipped_data %}
<h1> Dataset: {{ dataset.name }} </h1>
    <table>
        <tr>
            <th>Cell</th>
        </tr>
        {% for wet_cell, name in zipped_data %}
        <tr>
            <td>{{ name }}</td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>This dataset ({{ dataset.name }}) is empty.</p>
{% endif %}

<form action="{% url 'cell_database:view_dataset' pk=dataset.id%}" method="post">
    {% csrf_token %}
    Display Page: {{visuals_form.page_number}}
    Cells per Page: {{visuals_form.per_page}}
    Cells per Row: {{visuals_form.rows}}
    <input type="submit" name = 'plot_cells' value="Plot Cells">
</form>

{% if visual_data %}
    Showing page {{page_number}}/{{max_page_number}}.
        <table border="1">
            {% for zd in visual_data %}
                <tr valign="top">
                    {% for cell_id, image64 in zd %}
                        <td valign="top">

                            <a href="{% url 'view_cell_id'  cell_id  '' %}">
                                <img src="data:image/png;base64,{{image64}}" alt="If you see this, there was an error. Send email to Samuel.Buteau@dal.ca" width=200 height=auto />
                            </a>

                                 <font size="+2">{{cell_id}}</font>


                        </td>
                    {% endfor %}
                </tr>

            {% endfor %}
        </table>
{% endif %}

{% endblock %}